version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: compr-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  worker:
    build: .
    container_name: compr-worker
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
    volumes:
      - ./logs:/var/log/crosslisting
      - ./screenshots:/app/screenshots
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  redis-data:
    driver: local

networks:
  default:
    name: compr-network
